version: "3"
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/vehicules
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
